# Generated by rust2rpm
%bcond_with check
%global debug_package %{nil}

%global crate goblin

Name:           rust-%{crate}
Version:        0.0.22
Release:        3%{?dist}
Summary:        Impish, cross-platform, ELF, Mach-o, and PE binary parsing and loading crate

License:        MIT
URL:            https://crates.io/crates/goblin
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(log) >= 0.4.0 with crate(log) < 0.5.0)
BuildRequires:  (crate(plain/default) >= 0.2.3 with crate(plain/default) < 0.3.0)
BuildRequires:  (crate(scroll) >= 0.9.0 with crate(scroll) < 0.10.0)
BuildRequires:  (crate(scroll/derive) >= 0.9.0 with crate(scroll/derive) < 0.10.0)
BuildRequires:  (crate(scroll/std) >= 0.9.0 with crate(scroll/std) < 0.10.0)

%global _description \
An impish, cross-platform, ELF, Mach-o, and PE binary parsing and loading crate.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc CHANGELOG.md README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages
which use "alloc" feature of "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+archive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+archive-devel %{_description}

This package contains library source intended for building other packages
which use "archive" feature of "%{crate}" crate.

%files       -n %{name}+archive-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+elf32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+elf32-devel %{_description}

This package contains library source intended for building other packages
which use "elf32" feature of "%{crate}" crate.

%files       -n %{name}+elf32-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+elf64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+elf64-devel %{_description}

This package contains library source intended for building other packages
which use "elf64" feature of "%{crate}" crate.

%files       -n %{name}+elf64-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+endian_fd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+endian_fd-devel %{_description}

This package contains library source intended for building other packages
which use "endian_fd" feature of "%{crate}" crate.

%files       -n %{name}+endian_fd-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages
which use "log" feature of "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+mach32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mach32-devel %{_description}

This package contains library source intended for building other packages
which use "mach32" feature of "%{crate}" crate.

%files       -n %{name}+mach32-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+mach64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mach64-devel %{_description}

This package contains library source intended for building other packages
which use "mach64" feature of "%{crate}" crate.

%files       -n %{name}+mach64-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+pe32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pe32-devel %{_description}

This package contains library source intended for building other packages
which use "pe32" feature of "%{crate}" crate.

%files       -n %{name}+pe32-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+pe64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pe64-devel %{_description}

This package contains library source intended for building other packages
which use "pe64" feature of "%{crate}" crate.

%files       -n %{name}+pe64-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.22-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.22-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Apr 20 17:38:28 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.22-1
- Update to 0.0.22

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.19-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Nov 27 2018 Josh Stone <jistone@redhat.com> - 0.0.19-1
- Update to 0.0.19

* Tue Nov 13 2018 Josh Stone <jistone@redhat.com> - 0.0.17-2
- Adapt to new packaging

* Sat Jul 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.17-1
- Update to 0.0.17

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.15-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Mon Apr 23 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.15-1
- Update to 0.0.15

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.14-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Sat Feb 03 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.14-2
- Bump scroll to 0.9

* Thu Jan 18 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.14-1
- Update to 0.0.14

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.13-2
- Rebuild for rust-packaging v5

* Mon Jan 01 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.13-1
- Update to 0.0.13

* Mon Dec 04 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.12-2
- Fix tests

* Sun Dec 03 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.12-1
- Initial package
